/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distributedbankingclient;

import static distributedbankingclient.DistributedBankingClient.acc_num;
import static distributedbankingclient.DistributedBankingClient.tr_no;
import distributedbankmethods.DistributedBankMethods;
import java.io.DataInputStream;
import java.io.IOException;
import java.net.Socket;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Akash Thakrar
 */
public class DistributedBankingClient extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     * @throws java.rmi.RemoteException
     */
    public static ArrayList acc_num = new ArrayList();
    public static ArrayList accounts = new ArrayList();
    public static ArrayList tr_no = new ArrayList();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistributedBankingClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistributedBankingClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistributedBankingClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistributedBankingClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DistributedBankingClient().setVisible(true);
            }
        });
    }
    public DistributedBankingClient(DistributedBankMethods acc[],String ac_no[]) throws RemoteException, IOException {
        System.out.println(acc.length);
        for(int i=0;i<acc.length;i++){
            accounts.add(acc[i]);
            tr_no.add(0);
        }
        for(int i=0;i<ac_no.length;i++){
            acc_num.add(ac_no[i]);
        }
        initComponents();
        Receive r = new Receive();
        r.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dep_amt = new java.awt.TextField();
        cur_bal = new java.awt.TextField();
        with_amt = new java.awt.TextField();
        dep_btn = new java.awt.Button();
        chkbal_btn = new java.awt.Button();
        wit_btn = new java.awt.Button();
        label1 = new java.awt.Label();
        msg = new java.awt.Label();
        label3 = new java.awt.Label();
        deposit = new java.awt.Label();
        acc_no = new java.awt.TextField();
        deposit1 = new java.awt.Label();
        tr_btn = new java.awt.Button();
        jSeparator1 = new javax.swing.JSeparator();
        acc_no1 = new javax.swing.JTextField();
        tr_amt = new javax.swing.JTextField();
        acc_no2 = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cur_bal.setEditable(false);

        dep_btn.setLabel("Deposit");
        dep_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dep_btnActionPerformed(evt);
            }
        });

        chkbal_btn.setLabel("Check Balance");
        chkbal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbal_btnActionPerformed(evt);
            }
        });

        wit_btn.setLabel("Withdraw");
        wit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wit_btnActionPerformed(evt);
            }
        });

        label1.setText("Current Balance");

        msg.setAlignment(java.awt.Label.CENTER);
        msg.setText("information msgs goes here");

        label3.setText("Withdraw Amount");

        deposit.setName(""); // NOI18N
        deposit.setText("Deposit Amount");

        deposit1.setName(""); // NOI18N
        deposit1.setText("Account Number");

        tr_btn.setLabel("Transfer");
        tr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr_btnActionPerformed(evt);
            }
        });

        acc_no1.setName(""); // NOI18N

        tr_amt.setName(""); // NOI18N

        acc_no2.setName(""); // NOI18N

        label4.setText("Account No 2");

        label5.setText("Account No 1");

        label6.setText("Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deposit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dep_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dep_amt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(with_amt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acc_no, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cur_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkbal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acc_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acc_no2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tr_amt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tr_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acc_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deposit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dep_amt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dep_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(with_amt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(wit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cur_bal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(chkbal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tr_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(acc_no1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tr_amt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(acc_no2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        label1.getAccessibleContext().setAccessibleName("");
        label3.getAccessibleContext().setAccessibleName("");
        deposit.getAccessibleContext().setAccessibleName("");
        deposit1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dep_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dep_btnActionPerformed
        int dep=0;
        String acc;
        acc = acc_no.getText();
        if(!acc_num.contains(acc)){
            msg.setText("Account number invalid");
        }
        else{
            try{
                dep = Integer.parseInt(dep_amt.getText());
            }
            catch(Exception e){
                msg.setText("Please enter valid Deposit Amount");
            }
            if(dep<=0){
                msg.setText("Deposit amount invalid.");
            }
            else{
                int i = acc_num.indexOf(acc);
                DistributedBankMethods temp = (DistributedBankMethods)accounts.get(i);
                msg.setText("Please wait.. Processing transaction.");
                try {
                    if(temp.deposit(dep, ((int)tr_no.get(i)+1))){
                        tr_no.set(i, (int)tr_no.get(i)+1);
                        msg.setText("Transaction succeded");
                    }
                    else{
                        msg.setText("Transaction denied");
                    }
                } catch (RemoteException e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_dep_btnActionPerformed

    private void tr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr_btnActionPerformed
        int amt=0;
        String acc1,acc2;
        acc1 = acc_no1.getText();
        acc2 = acc_no2.getText();
        if(!acc_num.contains(acc1) || !acc_num.contains(acc2)){
            msg.setText("Account number 1 or 2 invalid");
        }
        else{
            try{
                amt = Integer.parseInt(tr_amt.getText());
            }
            catch(Exception e){
                msg.setText("Please enter valid amount");
            }
            if(amt <=0){
                msg.setText("Account number 1/2 or amount invalid");
            }
            else{
                msg.setText("Please wait.. Processing transaction.");
                int i1 = acc_num.indexOf(acc1);
                DistributedBankMethods temp1 = (DistributedBankMethods)accounts.get(i1);
                int i2 = acc_num.indexOf(acc2);
                DistributedBankMethods temp2 = (DistributedBankMethods)accounts.get(i2);
                try {
                    if(temp1.withdraw(amt, (int)tr_no.get(i1)+1)){
                        tr_no.set(i1, (int)tr_no.get(i1)+1);
                        if(temp2.deposit(amt, (int)tr_no.get(i2)+1)){
                            tr_no.set(i2, (int)tr_no.get(i2)+1);
                            msg.setText("Transaction successful");
                        }
                        else{
                            temp1.deposit(amt, (int)tr_no.get(i1)+1);
                        }
                    }
                } catch (RemoteException ex) {
                    Logger.getLogger(DistributedBankingClient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }            
        }

    }//GEN-LAST:event_tr_btnActionPerformed

    private void wit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wit_btnActionPerformed
        int wit=0;
        String acc;
        acc = acc_no.getText();
        if(!acc_num.contains(acc)){
            msg.setText("Account number invalid");
        }
        else{
            try{
                wit = Integer.parseInt(with_amt.getText());
            }
            catch(Exception e){
                msg.setText("Please enter valid Withdraw Amount");
            }
            if(wit<=0){
                msg.setText("Withdraw amount invalid.");
            }
            else{
                int i = acc_num.indexOf(acc);
                DistributedBankMethods temp = (DistributedBankMethods)accounts.get(i);
                msg.setText("Please wait.. Processing transaction.");
                try {
                    if(temp.withdraw(wit, ((int)tr_no.get(i)+1))){
                        tr_no.set(i, (int)tr_no.get(i)+1);
                        msg.setText("Transaction succeded");
                    }
                    else{
                        msg.setText("Transaction denied");
                    }
                } catch (RemoteException e) {
                    System.out.println(e);
                }
            }
        }
        
    }//GEN-LAST:event_wit_btnActionPerformed

    private void chkbal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbal_btnActionPerformed
        String acc;
        try{
            acc = acc_no.getText();
            if(!acc_num.contains(acc)){
                msg.setText("Account number invalid");
            }
            else{
                msg.setText("Please wait.. Processing transaction.");
                int i = acc_num.indexOf(acc);
                DistributedBankMethods temp = (DistributedBankMethods)accounts.get(i);
                int bal = temp.check_balance();
                cur_bal.setText(Integer.toString(bal));
            }
        }
        catch(Exception e){
            msg.setText("Please enter valid Account Number");
        }
    }//GEN-LAST:event_chkbal_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField acc_no;
    private javax.swing.JTextField acc_no1;
    private javax.swing.JTextField acc_no2;
    private java.awt.Button chkbal_btn;
    private java.awt.TextField cur_bal;
    private java.awt.TextField dep_amt;
    private java.awt.Button dep_btn;
    private java.awt.Label deposit;
    private java.awt.Label deposit1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label msg;
    private javax.swing.JTextField tr_amt;
    private java.awt.Button tr_btn;
    private java.awt.Button wit_btn;
    private java.awt.TextField with_amt;
    // End of variables declaration//GEN-END:variables
}
class Receive extends Thread{
    public void run(){
        Socket s;
        try {
            s = new Socket("localhost",5012);
            System.out.println("Connected to server");
            DataInputStream din=new DataInputStream(s.getInputStream());
            String temp;
            String t[];
            while(true){
                temp = din.readUTF();
                t = temp.split(" ");
                int i = DistributedBankingClient.acc_num.indexOf(t[0]);
                DistributedBankingClient.tr_no.set(i, Integer.parseInt(t[1]));
            }
        } catch (IOException e) {
            System.out.println(e);
        }
        
    }
}